### ISSUE TITLE
Installation error on MacOS

### ISSUE THREAD

**Issue by biranchi2018** [alankbi/detecto#22]
I installed using pip3

pip3 install detecto

```
from detecto import core, utils, visualize

image = utils.read_image('cat.jpeg')

model = core.Model()

labels, boxes, scores = model.predict_top(image)
visualize.show_labeled_image(image, boxes, labels)

```
===========================================================

I am getting the following errors :

biranchi@Biranchis-MBP Images $ python3 detect.py 
Traceback (most recent call last):
  File "detect.py", line 14, in <module>
    from detecto import core, utils, visualize
  File "/Users/biranchi/Library/Python/3.6/lib/python/site-packages/detecto/core.py", line 5, in <module>
    import torchvision
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/_C.cpython-36m-darwin.so, 2): Symbol not found: __ZN6caffe26detail36_typeMetaDataInstance_preallocated_0E
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/_C.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/_C.cpython-36m-darwin.so

**Comment by alankbi** [comment]
Could you try checking the installations of your torch and torchvision packages and if necessary reinstall them? Not sure if that'll help, but it's worth a try.

**Comment by alankbi** [comment]
Closing as this issue is over two weeks old.
