### ISSUE TITLE
IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by simeon9696** [alankbi/detecto#51]
**Describe the bug**
Trying to train a custom object detector when I get the error listed in the title. I think it's because it's not reading in my folders with the images and labels? I've tried` 'labels' ,'/labels' and '/labels/'`

**Code and Data**
```
from detecto import core, utils, visualize

# Images and XML files in separate folders
dataset = core.Dataset('labels/', 'images/')

image, target = dataset[0]
print(image, target)

model = core.Model(['bat', 'batter', 'pitch', 'field', 'player', 'scoreboard'])

model.fit(dataset)


# Specify the path to your image
image = utils.read_image('images/image0.jpg')
predictions = model.predict(image)

# predictions format: (labels, boxes, scores)
labels, boxes, scores = predictions

print(labels) 
print(boxes)
print(scores)
```

**Stacktrace**
```
Traceback (most recent call last):
  File "c:/Users/julis/Documents/ap-cricket/functions/train.py", line 9, in <module>
    image, target = dataset[0]
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\detecto\core.py", line 148, in __getitem__
    img_name = os.path.join(self._root_dir, self._csv.iloc[idx, 0])
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexing.py", line 1443, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexing.py", line 702, in _has_valid_tuple
    self._validate_key(k, i)
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexing.py", line 1352, in _validate_key
    self._validate_integer(key, axis)
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexing.py", line 1437, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```
**Environment:**
 - OS: Windows 10
 - Python version: 3.8
 - Detecto version:
 - torch version: 1.5.0
 - torchvision version : 0.6.0 

**Additional context**
Image name is : 'image0.jpg'
Label name is: 'image0.xml'

**Comment by alankbi** [comment]
Could you check the length of the dataset with `len(dataset)`? Also, make sure that you're running the code from the correct working directory, i.e. the labels and images folders are in the same working directory and not nested or in a higher-up directory.

**Comment by simeon9696** [comment]
Hi @alankbi I got past the error using the absolute paths

```
from detecto import core, utils, visualize
import matplotlib.pyplot as plt
import os

IMAGE_PATH = os.path.abspath(os.path.join(os.path.dirname( __file__ ), 'images'))
LABEL_PATH = os.path.abspath(os.path.join(os.path.dirname( __file__ ), 'labels'))


'''image = utils.read_image(os.path.join(IMAGE_PATH, 'image0.jpg'))
plt.imshow(image)
plt.show()'''



# Images and XML files in separate folders
dataset = core.Dataset(LABEL_PATH, IMAGE_PATH)

image, target = dataset[0]
print(image, target)

model = core.Model(['bat', 'batter', 'pitch', 'field', 'player', 'scoreboard'])

model.fit(dataset)


# Specify the path to your image
image = utils.read_image(os.path.join(IMAGE_PATH, 'image0.jpg'))
predictions = model.predict(image)

# predictions format: (labels, boxes, scores)
labels, boxes, scores = predictions

print(labels) 
print(boxes)
print(scores)
```

There is a new error however but I'll open a new issue since it may be unrelated

**Comment by bgriffen** [comment]
I have a similar issue except when creating a dataset from a CSV file. This file contains all required (`fout_train="train.csv"`):

`['filename', 'width', 'height', 'class', 'xmin', 'ymin', 'xmax', 'ymax', 'image_id']` 

but when I set this dataset

train_dataset = Dataset(fout_train)

and check the first item:

train_dataset[0]

```
In [7]: train_dataset[0]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-a0be1c17c5b0> in <module>
----> 1 train_dataset[0]

~/anaconda3/lib/python3.8/site-packages/detecto-1.2.1-py3.8.egg/detecto/core.py in __getitem__(self, idx)
    151         object_entries = self._csv.loc[self._csv['image_id'] == idx]
    152 
--> 153         img_name = os.path.join(self._root_dir, object_entries.iloc[0, 0])
    154         image = read_image(img_name)
    155 

~/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py in __getitem__(self, key)
   1760                 except (KeyError, IndexError, AttributeError):
   1761                     pass
-> 1762             return self._getitem_tuple(key)
   1763         else:
   1764             # we by definition only have the 0th axis

~/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py in _getitem_tuple(self, tup)
   2065     def _getitem_tuple(self, tup: Tuple):
   2066 
-> 2067         self._has_valid_tuple(tup)
   2068         try:
   2069             return self._getitem_lowerdim(tup)

~/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py in _has_valid_tuple(self, key)
    701                 raise IndexingError("Too many indexers")
    702             try:
--> 703                 self._validate_key(k, i)
    704             except ValueError:
    705                 raise ValueError(

~/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py in _validate_key(self, key, axis)
   1992             return
   1993         elif is_integer(key):
-> 1994             self._validate_integer(key, axis)
   1995         elif isinstance(key, tuple):
   1996             # a tuple should already have been caught by this point

~/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py in _validate_integer(self, key, axis)
   2061         len_axis = len(self.obj._get_axis(axis))
   2062         if key >= len_axis or key < -len_axis:
-> 2063             raise IndexError("single positional indexer is out-of-bounds")
   2064 
   2065     def _getitem_tuple(self, tup: Tuple):

IndexError: single positional indexer is out-of-bounds
```

The strange thing is that when I go to item 10, it returns the right result...

```
In [9]: train_dataset[10]
Out[9]: 
(tensor([[[-1.1247, -0.9020, -0.7650,  ..., -0.9020, -0.8507, -0.7993],
          [-0.8164, -0.5596, -0.3369,  ..., -1.0562, -1.0562, -1.0390],
          [-0.4397, -0.1828,  0.0569,  ..., -1.1760, -1.2103, -1.2103],
          ...,
          [-0.0972, -0.0801, -0.0458,  ..., -0.3369, -0.2342, -0.1999],
          [-0.0972, -0.0801, -0.0458,  ..., -0.2513, -0.1999, -0.1657],
          [-0.0972, -0.0972, -0.0801,  ..., -0.2171, -0.1828, -0.1828]],
 
         [[-1.0203, -0.7927, -0.6527,  ..., -0.7927, -0.7402, -0.6877],
          [-0.7052, -0.4426, -0.2150,  ..., -0.9503, -0.9503, -0.9328],
          [-0.3200, -0.0574,  0.1877,  ..., -1.0728, -1.1078, -1.1078],
          ...,
          [ 0.0301,  0.0476,  0.0826,  ..., -0.2150, -0.1099, -0.0749],
          [ 0.0301,  0.0476,  0.0826,  ..., -0.1275, -0.0749, -0.0399],
          [ 0.0301,  0.0301,  0.0476,  ..., -0.0924, -0.0574, -0.0574]],
 
         [[-0.7936, -0.5670, -0.4275,  ..., -0.5670, -0.5147, -0.4624],
          [-0.4798, -0.2184,  0.0082,  ..., -0.7238, -0.7238, -0.7064],
          [-0.0964,  0.1651,  0.4091,  ..., -0.8458, -0.8807, -0.8807],
          ...,
          [ 0.2522,  0.2696,  0.3045,  ...,  0.0082,  0.1128,  0.1476],
          [ 0.2522,  0.2696,  0.3045,  ...,  0.0953,  0.1476,  0.1825],
          [ 0.2522,  0.2522,  0.2696,  ...,  0.1302,  0.1651,  0.1651]]]),
 {'boxes': tensor([[374., 175., 428., 323.],
          [ 17., 145., 490., 352.],
          [ 70., 173., 127., 324.]], dtype=torch.float64),
  'labels': ['A', 'B', 'A']})
``

Is something going on in the ordering? Also, is there an example training file someone could point me to to ensure I have the right datatypes? I'm on `detecto-1.2.1`, `python==3.8` and Ubuntu==18.01`.

Thank you.

**Comment by bgriffen** [comment]
This has come up again in another revisit of detecto -- Out of curiosity @alankbi, is there a way to not make the strict requirement on `image_id` having to be both sequential and starting at 0 in both the training and test data? I would have thought after `train_test_split`, you should be able to just give both dataframes to DataLoader but it seems I then have to reassign all of the `image_ids` to satisfy that requirement. Presumably, the `image_ids` can just be abstracted away and just be created on the fly based on the `filename` column in each train/test dataframe going to the DataLoader. e.g. [just like this here](https://stackoverflow.com/a/51329888/1495869). i.e.

```
df['image_id'] = df.groupby(['filename']).ngroup()
```

I'm likely missing something behind the scenes that doesn't allow this, though. On my most recent issue relating to this (I think)...


```bash
Begin iterating over training dataset
  0%|                                                                                                        | 0/20 [00:00<?, ?it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-0d2a0526aafd> in <module>
      7       d.df[column] = d.df[column].astype('int32')
      8 
----> 9 d.train()

myprogram.py in train(self, epochs)
    146 
    147     def train(self,epochs=10):
--> 148         self.losses = self.model.fit(self.train_loader,self.test_loader,epochs=epochs,verbose=True)
    149 
    150     def save(self):

~/anaconda3/lib/python3.8/site-packages/detecto-1.2.1-py3.8.egg/detecto/core.py in fit(self, dataset, val_dataset, epochs, learning_rate, momentum, weight_decay, gamma, lr_step_size, verbose)
    516 
    517             iterable = tqdm(dataset, position=0, leave=True) if verbose else dataset
--> 518             for images, targets in iterable:
    519                 self._convert_to_int_labels(targets)
    520                 images, targets = self._to_device(images, targets)

~/anaconda3/lib/python3.8/site-packages/tqdm/std.py in __iter__(self)
   1176 
   1177         try:
-> 1178             for obj in iterable:
   1179                 yield obj
   1180                 # Update and possibly print the progressbar.

~/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py in __next__(self)
    519             if self._sampler_iter is None:
    520                 self._reset()
--> 521             data = self._next_data()
    522             self._num_yielded += 1
    523             if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    559     def _next_data(self):
    560         index = self._next_index()  # may raise StopIteration
--> 561         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    562         if self._pin_memory:
    563             data = _utils.pin_memory.pin_memory(data)

~/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

~/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

~/anaconda3/lib/python3.8/site-packages/detecto-1.2.1-py3.8.egg/detecto/core.py in __getitem__(self, idx)
    151         object_entries = self._csv.loc[self._csv['image_id'] == idx]
    152 
--> 153         img_name = os.path.join(self._root_dir, object_entries.iloc[0, 0])
    154         image = read_image(img_name)
    155 

~/anaconda3/lib/python3.8/posixpath.py in join(a, *p)
     88                 path += sep + b
     89     except (TypeError, AttributeError, BytesWarning):
---> 90         genericpath._check_arg_types('join', a, *p)
     91         raise
     92     return path

~/anaconda3/lib/python3.8/genericpath.py in _check_arg_types(funcname, *args)
    150             hasbytes = True
    151         else:
--> 152             raise TypeError(f'{funcname}() argument must be str, bytes, or '
    153                             f'os.PathLike object, not {s.__class__.__name__!r}') from None
    154     if hasstr and hasbytes:

TypeError: join() argument must be str, bytes, or os.PathLike object, not 'int64
```

test.csv

width | height | cluster | xmin | ymin | xmax | ymax | image_id | filename
-- | -- | -- | -- | -- | -- | -- | -- | --
53 | 133 | 1 | 453 | 274 | 505 | 407 | 0 | Position001.jpg
410 | 189 | 0 | 145 | 238 | 555 | 427 | 1 | Position046.jpg
62 | 127 | 0 | 444 | 273 | 506 | 400 | 1 | Position046.jpg
...

and train.csv

width | height | cluster | xmin | ymin | xmax | ymax | image_id | filename
-- | -- | -- | -- | -- | -- | -- | -- | --
53 | 133 | 1 | 453 | 274 | 505 | 407 | 0 | Position001.jpg
410 | 189 | 0 | 145 | 238 | 555 | 427 | 1 | Position046.jpg
62 | 127 | 0 | 444 | 273 | 506 | 400 | 1 | Position046.jpg
56 | 123 | 0 | 200 | 265 | 256 | 388 | 1 | Position046.jpg
413 | 192 | 0 | 148 | 226 | 562 | 418 | 2 | Position028.jpg
...

As a check...

```
In [2]: d.train_dataset
Out[2]: <detecto.core.Dataset at 0x7f2af6a5b5e0>

In [3]: d.train_dataset[0]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-c58fa18afada> in <module>
----> 1 d.train_dataset[0]

~/anaconda3/lib/python3.8/site-packages/detecto-1.2.1-py3.8.egg/detecto/core.py in __getitem__(self, idx)
    151         object_entries = self._csv.loc[self._csv['image_id'] == idx]
    152 
--> 153         img_name = os.path.join(self._root_dir, object_entries.iloc[0, 0])
    154         image = read_image(img_name)
    155 

~/anaconda3/lib/python3.8/posixpath.py in join(a, *p)
     88                 path += sep + b
     89     except (TypeError, AttributeError, BytesWarning):
---> 90         genericpath._check_arg_types('join', a, *p)
     91         raise
     92     return path

~/anaconda3/lib/python3.8/genericpath.py in _check_arg_types(funcname, *args)
    150             hasbytes = True
    151         else:
--> 152             raise TypeError(f'{funcname}() argument must be str, bytes, or '
    153                             f'os.PathLike object, not {s.__class__.__name__!r}') from None
    154     if hasstr and hasbytes:

TypeError: join() argument must be str, bytes, or os.PathLike object, not 'int64'
```

These being assigned here in my program...

```python
        self.train_dataset = Dataset(self.fout_train,transform=self.default_trans)
        self.test_dataset = Dataset(self.fout_test) 
        
        self.train_loader = DataLoader(self.train_dataset, batch_size=batch_size, shuffle=True)
        self.test_loader = DataLoader(self.test_dataset, shuffle=True)
```

**Update** It comes down to `iloc` indexing. So when the comments/docs [link](https://github.com/alankbi/detecto/blob/c57b5fe3037bf8bc077a41d74c769dd5b164b994/detecto/core.py#L122) say the csv file contains....

`CSV file contains: filename, width, height, class, xmin, ymin, xmax, ymax`

The actual order of those columns matters because of 

`--> 153         img_name = os.path.join(self._root_dir, object_entries.iloc[0, 0])` in core.py 

General comment though - shouldn't this just be `object_entries.loc[0, 'filename']` so it's agnostic to what order the columns are put in. Also, curious as to people's thoughts on the nrgoup() function being run to just generate the image_ids in the backend?

**Comment by alankbi** [comment]
Fair points on both the `iloc` indexing and abstracting away `image_id` with `ngroup` - I think both are very good ideas. 

Is that something you'd be interested in implementing? If so, I'd be happy to accept a PR and include it sometime in the next release. If not, I can make a note of it and try adding it sometime in the future, although that might not be for several months

**Comment by bgriffen** [comment]
I'm also caught up at the moment but will take a look when I can too!
