### ISSUE TITLE
!_src.empty() in function 'cv::cvtColor'

### ISSUE THREAD

**Issue by simeon9696** [alankbi/detecto#54]
**Describe the bug**
During training at model.fit(dataset) OpenCV gives an error `cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'`

**Code and Data**
```
from detecto import core, utils, visualize
import matplotlib.pyplot as plt
import os

IMAGE_PATH = os.path.abspath(os.path.join(os.path.dirname( __file__ ), 'images'))
LABEL_PATH = os.path.abspath(os.path.join(os.path.dirname( __file__ ), 'labels'))


'''image = utils.read_image(os.path.join(IMAGE_PATH, 'image0.jpg'))
plt.imshow(image)
plt.show()'''



# Images and XML files in separate folders
dataset = core.Dataset(LABEL_PATH, IMAGE_PATH)

image, target = dataset[0]
print(image, target)

model = core.Model(['bat', 'batter', 'pitch', 'field', 'player', 'scoreboard', 'stumps'])

model.fit(dataset)


# Specify the path to your image
image = utils.read_image(os.path.join(IMAGE_PATH, 'image-3361.jpg'))
predictions = model.predict(image)

# predictions format: (labels, boxes, scores)
labels, boxes, scores = predictions

print(labels) 
print(boxes)
print(scores)
```

It prints the image and target so we know it's reading in the dataset:
```
tensor([[[-0.9705, -0.6794, -0.5596,  ..., -0.3541, -0.9534, -2.1008],
         [-0.9705, -0.6794, -0.5596,  ..., -0.3712, -0.9534, -2.1008],
         [-0.9705, -0.6794, -0.5596,  ..., -0.3541, -0.9363, -2.1008],
         ...,
         [-0.9192, -0.3369, -0.5253,  ..., -0.0801, -0.7650, -2.1008],
         [-0.9192, -0.3369, -0.5253,  ..., -0.0801, -0.7650, -2.1008],
         [-0.9192, -0.3369, -0.5253,  ..., -0.0801, -0.7650, -2.1008]],

        [[-0.3725, -0.0749,  0.0476,  ...,  0.1877, -0.4601, -1.6506],
         [-0.3725, -0.0749,  0.0476,  ...,  0.1702, -0.4601, -1.6506],
         [-0.3725, -0.0749,  0.0476,  ...,  0.1877, -0.4426, -1.6506],
         ...,
         [-0.3375,  0.2577,  0.0651,  ...,  0.3627, -0.3725, -1.7731],
         [-0.3375,  0.2577,  0.0651,  ...,  0.3627, -0.3725, -1.7731],
         [-0.3375,  0.2577,  0.0651,  ...,  0.3627, -0.3725, -1.7731]],

        [[-1.2119, -0.9156, -0.7936,  ..., -0.4275, -0.8633, -1.8044],
         [-1.2119, -0.9156, -0.7936,  ..., -0.4450, -0.8633, -1.8044],
         [-1.2119, -0.9156, -0.7936,  ..., -0.4275, -0.8458, -1.8044],
         ...,
         [-1.3513, -0.7587, -0.9504,  ..., -0.3230, -0.7761, -1.8044],
         [-1.3513, -0.7587, -0.9504,  ..., -0.3230, -0.7761, -1.8044],
         [-1.3513, -0.7587, -0.9504,  ..., -0.3230, -0.7761, -1.8044]]]) {'boxes': tensor([[795, 385, 835, 462]]), 'labels': 'bat'}
```
Stacktrace
```
Traceback (most recent call last):
  File "potato.py", line 23, in <module>
    model.fit(dataset)
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\detecto\core.py", line 468, in fit
    for images, targets in dataset:
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\detecto\core.py", line 149, in __getitem__
    image = read_image(img_name)
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\detecto\utils.py", line 134, in read_image
    return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
```
After some research this is when OpenCV can't find the image but I don't understand how this is possible since it prints the first item in the dataset list

**Environment:**
 - OS:  Windows 10
 - Python version: 3.8
 - Detecto version: latest 
 - torch version: 1.5.0
 - torchvision version: 0.6.0

**Additional context**
Image name is : 'image-3361.jpg'
Label name is: 'image-3361.xml'

**Comment by terpdaderp** [comment]
I have this issue as well attempted to downgrade OpenCV but to no avail.

**Comment by alankbi** [comment]
Does reading the images manually work for all indices in the dataset?

**Comment by simeon9696** [comment]
> Does reading the images manually work for all indices in the dataset?

@alankbi  I'm not sure what  you mean? The preview showed up for image-1 and image-3361 so I didn't think it would have any issue for those inbetween. Should I try to print an index other than zero? For example: 

```
image, target = dataset[75]
print(image, target)
```

**Comment by simeon9696** [comment]
> > Does reading the images manually work for all indices in the dataset?
> 
> @alankbi I'm not sure what you mean? The preview showed up for image-1 and image-3361 so I didn't think it would have any issue for those inbetween. Should I try to print an index other than zero? For example:
> 
> ```
> image, target = dataset[75]
> print(image, target)
> ```

If I do the above I get the following output. The warning that's attached was there the last time as well. 
```
tensor([[[-0.9705, -0.5082, -0.4054,  ..., -0.2513, -0.9020, -2.1179], 
         [-0.9877, -0.5082, -0.4054,  ..., -0.2513, -0.9020, -2.1179], 
         [-0.9877, -0.5253, -0.4054,  ..., -0.2513, -0.9192, -2.1179], 
         ...,
         [-0.9705, -0.4226, -0.4911,  ..., -0.0629, -0.8507, -2.1179], 
         [-0.9534, -0.4054, -0.4739,  ..., -0.0629, -0.8507, -2.1179], 
         [-0.9534, -0.4054, -0.4739,  ..., -0.0629, -0.8507, -2.1179]],

        [[-0.3550,  0.1176,  0.2227,  ...,  0.3627, -0.3725, -1.6506], 
         [-0.3725,  0.1176,  0.2227,  ...,  0.3627, -0.3725, -1.6506], 
         [-0.3725,  0.1001,  0.2227,  ...,  0.3627, -0.3901, -1.6506],
         ...,
         [-0.4776,  0.0826,  0.0126,  ...,  0.3627, -0.4951, -1.8606],
         [-0.4601,  0.1001,  0.0301,  ...,  0.3627, -0.4951, -1.8606],
         [-0.4601,  0.1001,  0.0301,  ...,  0.3627, -0.4951, -1.8606]],

        [[-1.2990, -0.8284, -0.7238,  ..., -0.2532, -0.7413, -1.8044],
         [-1.3164, -0.8284, -0.7238,  ..., -0.2532, -0.7413, -1.8044],
         [-1.3164, -0.8458, -0.7238,  ..., -0.2532, -0.7587, -1.8044],
         ...,
         [-1.5256, -0.9678, -1.0376,  ..., -0.3753, -0.8807, -1.8044],
         [-1.5081, -0.9504, -1.0201,  ..., -0.3753, -0.8807, -1.8044],
         [-1.5081, -0.9504, -1.0201,  ..., -0.3753, -0.8807, -1.8044]]]) {'boxes': tensor([[849, 448, 864, 552]]), 'labels': 'bat'}
C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\torchvision\ops\boxes.py:101: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  ..\torch\csrc\utils\python_arg_parser.cpp:766.)
  keep = keep.nonzero().squeeze(1)
```

**Comment by alankbi** [comment]
Yeah, I meant looping through all indices of the dataset and seeing if any specific indices threw an error. That way you might be able to isolate if it's an issue with a specific image or just as a whole something is wrong. 

If doing that doesn't trigger any errors, does the error still happen if you use `torch==1.4.0` and `torchvision==0.5.0`?

**Comment by simeon9696** [comment]
@alankbi So there are 94 images in the folder. I printed it out as you suggested and it failed at 67. I printed the index as well hence the 67 in the output below. 

```
67
tensor([[[-0.9705, -0.5082, -0.4054,  ..., -0.2513, -0.9020, -2.1179],
         [-0.9877, -0.5082, -0.4054,  ..., -0.2513, -0.9020, -2.1179],
         [-0.9877, -0.5253, -0.4054,  ..., -0.2513, -0.9192, -2.1179],
         ...,
         [-1.0733, -0.4397, -0.5082,  ..., -0.1314, -0.8507, -2.1179],
         [-1.0904, -0.4568, -0.5253,  ..., -0.1314, -0.8507, -2.1179],
         [-1.0904, -0.4568, -0.5253,  ..., -0.1314, -0.8507, -2.1179]],

        [[-0.3550,  0.1176,  0.2227,  ...,  0.3627, -0.3725, -1.6506],
         [-0.3725,  0.1176,  0.2227,  ...,  0.3627, -0.3725, -1.6506],
         [-0.3725,  0.1001,  0.2227,  ...,  0.3627, -0.3901, -1.6506],
         ...,
         [-0.5126,  0.1352,  0.0826,  ...,  0.3102, -0.5651, -1.9307],
         [-0.5301,  0.1176,  0.0651,  ...,  0.3102, -0.5651, -1.9307],
         [-0.5301,  0.1176,  0.0651,  ...,  0.3102, -0.5651, -1.9307]],

        [[-1.2990, -0.8284, -0.7238,  ..., -0.2532, -0.7413, -1.8044],
         [-1.3164, -0.8284, -0.7238,  ..., -0.2532, -0.7413, -1.8044],
         [-1.3164, -0.8458, -0.7238,  ..., -0.2532, -0.7587, -1.8044],
         ...,
         [-1.4210, -0.7761, -0.8633,  ..., -0.3404, -0.8110, -1.8044],
         [-1.4384, -0.7936, -0.8807,  ..., -0.3404, -0.8110, -1.8044],
         [-1.4384, -0.7936, -0.8807,  ..., -0.3404, -0.8110, -1.8044]]]) {'boxes': tensor([[604, 207, 621, 217]]), 'labels': 'bat'}
Traceback (most recent call last):
  File "c:/Users/julis/Documents/ap-cricket/functions/potato.py", line 18, in <module>
    for i in dataset:
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\detecto\core.py", line 149, in __getitem__
    image = read_image(img_name)
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\detecto\utils.py", line 134, in read_image
    return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
```

**Comment by simeon9696** [comment]
Hi @alankbi so there are 94 images in the folder. I printed it out as you suggested and it failed at 67. I printed the index as well hence the 67 in the output below.

```
67
tensor([[[-0.9705, -0.5082, -0.4054,  ..., -0.2513, -0.9020, -2.1179],
         [-0.9877, -0.5082, -0.4054,  ..., -0.2513, -0.9020, -2.1179],
         [-0.9877, -0.5253, -0.4054,  ..., -0.2513, -0.9192, -2.1179],
         ...,
         [-1.0733, -0.4397, -0.5082,  ..., -0.1314, -0.8507, -2.1179],
         [-1.0904, -0.4568, -0.5253,  ..., -0.1314, -0.8507, -2.1179],
         [-1.0904, -0.4568, -0.5253,  ..., -0.1314, -0.8507, -2.1179]],

        [[-0.3550,  0.1176,  0.2227,  ...,  0.3627, -0.3725, -1.6506],
         [-0.3725,  0.1176,  0.2227,  ...,  0.3627, -0.3725, -1.6506],
         [-0.3725,  0.1001,  0.2227,  ...,  0.3627, -0.3901, -1.6506],
         ...,
         [-0.5126,  0.1352,  0.0826,  ...,  0.3102, -0.5651, -1.9307],
         [-0.5301,  0.1176,  0.0651,  ...,  0.3102, -0.5651, -1.9307],
         [-0.5301,  0.1176,  0.0651,  ...,  0.3102, -0.5651, -1.9307]],

        [[-1.2990, -0.8284, -0.7238,  ..., -0.2532, -0.7413, -1.8044],
         [-1.3164, -0.8284, -0.7238,  ..., -0.2532, -0.7413, -1.8044],
         [-1.3164, -0.8458, -0.7238,  ..., -0.2532, -0.7587, -1.8044],
         ...,
         [-1.4210, -0.7761, -0.8633,  ..., -0.3404, -0.8110, -1.8044],
         [-1.4384, -0.7936, -0.8807,  ..., -0.3404, -0.8110, -1.8044],
         [-1.4384, -0.7936, -0.8807,  ..., -0.3404, -0.8110, -1.8044]]]) {'boxes': tensor([[604, 207, 621, 217]]), 'labels': 'bat'}
Traceback (most recent call last):
  File "c:/Users/julis/Documents/ap-cricket/functions/potato.py", line 18, in <module>
    for i in dataset:
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\detecto\core.py", line 149, in __getitem__
    image = read_image(img_name)
  File "C:\Users\julis\AppData\Local\Programs\Python\Python38\lib\site-packages\detecto\utils.py", line 134, in read_image
    return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
```

**Comment by alankbi** [comment]
I ran through all the images from your notebook and it looks like the only image that fails is that of `dataset[80]`, which is the image `image-1433.jpg`. Could you try removing just that image/XML file from your folders?

**Comment by alankbi** [comment]
More specifically, it looks like your `images` folder is straight-up missing an `image-1433.jpg`, whereas you probably have an XML file that references that image. I think to fix this bug, all you should have to do is either delete that label file or find the missing image.

**Comment by simeon9696** [comment]
@alankbi I just checked andlike you said there isn't an `image-1433.jpg`  but there isn't a corresponding `image-1433.xml` in `labels` either.

**Comment by alankbi** [comment]
Looks like `image-1256.xml` is the root of the problem: 

```xml
<annotation>
	<folder>blurry</folder>
	<filename>image-1433.jpg</filename>
	<path>C:\Users\julis\Documents\ap-cricket\images\blurry\image-1433.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>1280</width>
		<height>720</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>bat</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>762</xmin>
			<ymin>459</ymin>
			<xmax>787</xmax>
			<ymax>566</ymax>
		</bndbox>
	</object>
</annotation>
```

**Comment by simeon9696** [comment]
> Looks like `image-1256.xml` is the root of the problem:
> 
> ```
> <annotation>
> 	<folder>blurry</folder>
> 	<filename>image-1433.jpg</filename>
> 	<path>C:\Users\julis\Documents\ap-cricket\images\blurry\image-1433.jpg</path>
> 	<source>
> 		<database>Unknown</database>
> 	</source>
> 	<size>
> 		<width>1280</width>
> 		<height>720</height>
> 		<depth>3</depth>
> 	</size>
> 	<segmented>0</segmented>
> 	<object>
> 		<name>bat</name>
> 		<pose>Unspecified</pose>
> 		<truncated>0</truncated>
> 		<difficult>0</difficult>
> 		<bndbox>
> 			<xmin>762</xmin>
> 			<ymin>459</ymin>
> 			<xmax>787</xmax>
> 			<ymax>566</ymax>
> 		</bndbox>
> 	</object>
> </annotation>
> ```

So deleting that `image-1256.xml` file and that `image-1256.jpg` file should fix everything? After this is over do you mind expanding on your thought process to get this fixed?

**Comment by alankbi** [comment]
I think just deleting `image-1256.xml` should be able to solve it. Basically, when you pass in the XML files to the dataset, it constructs a dataframe that references all of the info stored in those XML files. When you access something like `dataset[80]`, it'll access row 80 in that dataframe (in other words, the information from your 80th XML file), which includes a path to the associated image, and tries to return that image as well as the info about labels/bounding boxes. However, since that 80th XML file has a path to a nonexistent image, you end up getting that cv2 error when the dataset tries to read it. Therefore, once you remove or update the incorrect XML file, your dataset should go back to working as normal.

**Comment by simeon9696** [comment]
@alankbi  I can't thank you enough! Everything went through without a problem. I'll experiment with the latest version of `torch `and `torchvision `just to see if that causes an issue or not. 

The final output on the test image: 
```
['bat', 'bat', 'scoreboard']
tensor([[627.9774, 141.0100, 682.6935, 268.3948],
        [624.8055, 112.9684, 699.4097, 306.0868],
        [178.3388, 628.6505, 523.0804, 695.6808]])
tensor([0.9369, 0.1847, 0.0588])
```
