### ISSUE TITLE
error at setup.py

### ISSUE THREAD

**Issue by PatxiofromAlphensign** [alankbi/detecto#9]
in the CLI, it's showing `ERROR: torchvision 0.5.0 has requirement torch==1.4.0, but you'll have torch 0.1.2.post2 which is incompatible.`

could this be the reason why I'm getting this at `setup.py`

`Installing collected packages: torch, torchvision, imageio, scipy, PyWavelets, networkx, scikit-image, opencv-python, detecto
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\aissy\\AppData\\Local\\Temp\\pip-install-p4rkthbk\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\aissy\\AppData\\Local\\Temp\\pip-install-p4rkthbk\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\aissy\AppData\Local\Temp\pip-record-xhysinhv\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Include\torch'
         cwd: C:\Users\aissy\AppData\Local\Temp\pip-install-p4rkthbk\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\aissy\AppData\Local\Temp\pip-install-p4rkthbk\torch\setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\aissy\AppData\Local\Temp\pip-install-p4rkthbk\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\aissy\AppData\Local\Temp\pip-install-p4rkthbk\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\aissy\\AppData\\Local\\Temp\\pip-install-p4rkthbk\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\aissy\\AppData\\Local\\Temp\\pip-install-p4rkthbk\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\aissy\AppData\Local\Temp\pip-record-xhysinhv\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Include\torch' Check the logs for full command output.`

**Comment by alankbi** [comment]
Could you try downloading the latest version of PyTorch and see if that fixes the issue? Instructions for how to do so are here: https://pytorch.org/get-started/locally/

**Comment by alankbi** [comment]
Closing this as it seems to be an issue with installing one of Detecto's dependencies rather than Detecto itself. Feel free to reopen if a related issue comes up though!
